/**
 * Shopify headless bridge — maps the frontend catalog (products.ts) to Shopify
 * variant IDs and builds tokenless cart-permalink checkout URLs.
 *
 * Architecture: the entire storefront (browse, PDP, cart) stays on Next/Vercel.
 * At final checkout we hand the cart to Shopify via a cart permalink
 * (`/cart/{variantId}:{qty},…`) so Shopify owns payment, orders, inventory and
 * the admin panel. No API token ships to the browser — permalinks are public.
 *
 * The variant map is generated by scripts/verify-shopify-map.ts from the live
 * Shopify catalog (Admin API) and cross-checked: every purchasable frontend
 * variant resolves to a real Shopify variant (52/52 at time of writing).
 *
 * Gated behind NEXT_PUBLIC_USE_SHOPIFY_CHECKOUT so the existing Razorpay/COD
 * checkout stays the default until we deliberately flip over.
 */
import { PRODUCTS } from "./products";

export const SHOPIFY_STORE = "8yyp1g-0a.myshopify.com";

/** Flip checkout from the custom Razorpay flow to Shopify's hosted checkout. */
export const USE_SHOPIFY_CHECKOUT =
  process.env.NEXT_PUBLIC_USE_SHOPIFY_CHECKOUT === "1";

/**
 * key → numeric Shopify variant id.
 * key = `${sku.slug}|${colorSlug}` for colored SKUs, or `${sku.slug}` for
 * single-variant SKUs. Generated from the live Shopify catalog.
 */
export const SHOPIFY_VARIANTS: Record<string, string> = {
  "pocket-bmw|white": "47458279981187",
  "pocket-bmw|blue": "47458280013955",
  "pocket-bmw|black": "47458280046723",
  "pocket-porsche|dark-blue": "47458278965379",
  "pocket-porsche|green": "47458278998147",
  "pocket-porsche|yellow": "47458279030915",
  "pocket-porsche|multi": "47458279063683",
  "pocket-thar|blue": "47458277687427",
  "pocket-thar|yellow": "47458277720195",
  "pocket-thar|white": "47458277752963",
  "pocket-thar|black": "47458277785731",
  "pocket-monster|blue": "47458275229827",
  "pocket-monster|yellow": "47458275262595",
  "pocket-monster|white-red": "47458275295363",
  "pocket-monster|multi": "47458275328131",
  "pocket-monster|red-orange": "47458275360899",
  "pocket-f1-classic|white": "47458277130371",
  "pocket-f1-classic|red": "47458277163139",
  "cybertruck-camper": "47458283847811",
  "ferrari-drift|red": "47458284929155",
  "ferrari-drift|black": "47458284961923",
  "ferrari-drift|white": "47458284994691",
  "ferrari-drift|yellow": "47458285027459",
  "mini-atv": "47458287485059",
  "mini-bmw-m4|silver": "47458287812739",
  "mini-bmw-m4|black": "47458287845507",
  "mini-land-rover|sand": "47458290434179",
  "mini-land-rover|lilac": "47458290466947",
  "mini-porsche|white": "47458291843203",
  "mini-porsche|blue": "47458291875971",
  "rc-tractor|blue": "47458293121155",
  "rc-tractor|yellow": "47458293153923",
  "tiger-monster": "47458293383299",
  "toyota-trueno|red": "47458293907587",
  "toyota-trueno|white": "47458293940355",
  "samtop-camera|black": "47458295709827",
  "samtop-camera|white": "47458295742595",
  "drift-inferno": "47458296299651",
  "dares-azure": "47458296758403",
  "bmw-m4-dtm": "47458296922243",
  "extreme-street-drift": "47458298495107",
  "gtr-gt3": "47458299609219",
  "mercedes-amg-gt3": "47458301575299",
  "lamborghini-vision-gt": "47458302034051",
  "toyota-ae86-20": "47458302197891",
  "track-rover": "47458303115395",
  "vw-polo-95-white": "47458310291587",
  "vw-polo-95-blue": "47458313044099",
  "construction-3pack": "47458314322051",
  "mining-truck": "47458303606915",
  "rc-excavator": "47458305998979",
  "rc-forklift": "47458310226051",
};

/** Resolve a cart line (frontend skuId + color slug) to a Shopify variant id. */
export function shopifyVariantId(
  skuId: string,
  variantSlug: string | null,
): string | null {
  const sku = PRODUCTS.find((p) => p.id === skuId);
  if (!sku) return null;
  if (variantSlug) {
    const keyed = SHOPIFY_VARIANTS[`${sku.slug}|${variantSlug}`];
    if (keyed) return keyed;
  }
  // single-variant SKU, or colored SKU with no color chosen → base handle
  return SHOPIFY_VARIANTS[sku.slug] ?? null;
}

export type ShopifyCartInput = {
  skuId: string;
  variantSlug: string | null;
  qty: number;
};

/**
 * Build a tokenless Shopify cart permalink from cart lines. Adds every line to
 * the Shopify cart and lands the buyer on Shopify's checkout. Returns null if
 * no line resolves to a variant (caller should fall back to the custom flow).
 */
export function buildShopifyCartUrl(items: ShopifyCartInput[]): string | null {
  const parts: string[] = [];
  for (const i of items) {
    const id = shopifyVariantId(i.skuId, i.variantSlug);
    if (id) parts.push(`${id}:${Math.max(1, Math.floor(i.qty))}`);
  }
  if (!parts.length) return null;
  // `?checkout[email]` etc. could be appended later; storefront=… avoids the
  // "cart" interstitial on some themes. Keep it minimal + reliable for now.
  return `https://${SHOPIFY_STORE}/cart/${parts.join(",")}`;
}
